name: Bug Report
description: Report a reproducible bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Please fill out all sections for faster resolution."
  - type: input
    id: env
    attributes:
      label: Environment
      description: OS, language version, dependency versions, etc.
      placeholder: e.g., macOS 14.3, Node 20, Python 3.11
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe step-by-step how to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
